name: Deploy Discord Bot

on:
  push:
    branches: [main]      # 每次 push 到 main 分支自動觸發
  workflow_dispatch:       # 允許手動觸發

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot
      env:
        MIKUTOKEN: ${{ secrets.MIKUTOKEN }}
      run: python bot.py
